name: Ethrex Latest Release

on:
  workflow_dispatch:
  release:
    types:
      - edited

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  get_latest_release:
    name: "Get latest release tag"
    runs-on: ubuntu-latest
    outputs:
      latest_tag: ${{ steps.get_latest_release.outputs.latest_tag }}

    steps:
      - name: Get latest release tag from GH API
        id: get_latest_release
        run: |
          tag=$(curl -s https://api.github.com/repos/${{ env.IMAGE_NAME }}/releases/latest | jq -r .tag_name)
          echo "Latest release tag: $tag"
          echo "latest_tag=$tag" >> $GITHUB_OUTPUT

  retag_docker_images:
    name: "Tag latest Docker images"
    runs-on: ubuntu-latest
    needs: [get_latest_release]
    #if: ${{ needs.get_latest_release.outputs.latest_tag == github.event.release.tag_name && github.event.changes.tag_name.from }}

    steps:
      - name: Set tags
        run: |
          echo "test"

  publish-apt:
    needs:
      - retag_docker_images
    uses: lambdaclass/ethrex-apt/.github/workflows/publish-apt.yml@main
    permissions:
      contents: write
      actions: write
